[project]
name = "bikesim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kaleb.grove", email = "kwolfgrove@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "matplotlib>=3.11.1",
    "requests>=2.34.2",
]

[project.scripts]
bikesim = "bikesim:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
